### ISSUE TITLE
create wireframes

### ISSUE THREAD

**Issue by jackcrosbie** [jackcrosbie/hackathon-feb#3]

**Comment by rstan-dev** [comment]
Home V1
![Image](https://user-images.githubusercontent.com/118801685/219602542-d133555d-268a-402a-a37f-6f3cd232c5db.png)


Donations V1
![Image](https://user-images.githubusercontent.com/118801685/219602564-61219534-9244-4b97-bd53-e19a4719f8ed.png)


Event Ideas v1
![Image](https://user-images.githubusercontent.com/118801685/219602587-3d50fd0b-e0d8-4e18-971f-03804d9f4af7.png)


Socials V1
![Image](https://user-images.githubusercontent.com/118801685/219602598-9d46f754-32ce-44db-a234-6b6b69820bb5.png)


Revised Donations & Social Page Combined V2

![Image](https://user-images.githubusercontent.com/118801685/219602644-71b7d2ac-cd8e-4f46-9de2-a5cf55a61fb6.png)


Revised Events Page V2
![Image](https://user-images.githubusercontent.com/118801685/219602663-b1cd1ba9-e8aa-40c0-9ada-d00f1fdbebbe.png)

**Comment by rstan-dev** [comment]
Events Page V3

![Image](https://user-images.githubusercontent.com/118801685/219603605-c6365925-8381-40c1-be26-b46bc5783403.png)
