### ISSUE TITLE
pick colours and fonts for site

### ISSUE THREAD

**Issue by jackcrosbie** [jackcrosbie/hackathon-feb#4]

**Comment by rstan-dev** [comment]
Orange: #ff7e20
Grey:  #585b5d


Fonts, & elements:
Headlines - Helvetica Lt Std Condensed and Helvetica Std Bold Condensed
Icons, buttons and call to action links
Orange: #ff7e20

Paragraph text: Helvetica Lt Std Roman
Grey:  #585b5d
